In [10]:
from lib import read_file

import numpy as np
import matplotlib.pyplot as plt

In [34]:
lines = read_file("11_input.txt")
lines

['.......................................#..........................................................#......................................#..',
 '.....................#................................#.....................................................................................',
 '....#.....#...................#...............#....................#.....................#.....................#....................#.......',
 '............................................................................................................................................',
 '.................#......................................................#......#..............#....................#........................',
 '......................................#.....................................................................................................',
 '.......................................................#...................................................#..............#.....

In [35]:
arr = np.zeros((len(lines), len(lines[0])))

for i in range(len(lines)):
    for j in range(len(lines[0])):
        if lines[i][j] == "#":
            arr[i, j] = 1

# Expand galaxy
def expand(arr):
    inserts = 0
    for i in range(arr.shape[0]):
        idx = i + inserts
        if np.all(arr[idx, :] == 0):
            arr = np.insert(arr, idx, np.zeros(arr.shape[1]), axis=0)
            inserts += 1
    return arr

arr = expand(arr)
arr = expand(arr.T).T

print(arr)

[[0. 0. 0. ... 1. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 1. 0. 0.]
 [0. 0. 1. ... 0. 0. 0.]]


In [36]:
distance = 0
xs, ys = np.where(arr)
for x0, y0 in zip(xs, ys):
    for x1, y1 in zip(xs, ys):
        distance += abs(x1 - x0) + abs(y1 - y0)

distance / 2


9623138.0

# Part 2

In [41]:
lines = read_file("11_input.txt")
lines

arr = np.zeros((len(lines), len(lines[0])))

for i in range(len(lines)):
    for j in range(len(lines[0])):
        if lines[i][j] == "#":
            arr[i, j] = 1

# Get rows/cols where galaxy expands
def get_expansion_idxs(arr):
    idxs = []
    for i in range(arr.shape[0]):
        if np.all(arr[i, :] == 0):
            idxs.append(i)
    return idxs

idxs_0 = get_expansion_idxs(arr)
idxs_1 = get_expansion_idxs(arr.T)


[3, 7, 27, 32, 36, 50, 51, 59, 60, 90, 93]

In [42]:
distance = 0
xs, ys = np.where(arr)
for x0, y0 in zip(xs, ys):
    for x1, y1 in zip(xs, ys):
        for x in range(min(x0, x1), max(x0, x1)):
            if x in idxs_0:
                distance += 1e6
            else:
                distance += 1
        for y in range(min(y0, y1), max(y0, y1)):
            if y in idxs_1:
                distance += 1e6
            else:
                distance += 1

distance / 2

726820169514.0